import main
import pprint


def test_compute():
    res = main.compute("tests/82318c24-3f36-424f-9b29-c1e7e05acfe5.pdf", "82318c24-3f36-424f-9b29-c1e7e05acfe5")
    pprint.pprint(res)
    assert res == {
        "zipFile": "82318c24-3f36-424f-9b29-c1e7e05acfe5.zip",
        "data": [
            {
                "qrcode": {
                    "matricule": 20072,
                    "version": "A",
                    "lessonId": "82318c24-3f36-424f-9b29-c1e7e05acfe5",
                },
                "answers": [
                    [False, False, False, False, True, False],
                    [False, False, False, False, True, False],
                    [False, True, False, False, False, False],
                    [False, False, True, False, False, False],
                    [False, True, False, False, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, False, True, False],
                    [False, True, False, False, False, False],
                    [False, False, False, False, True, False],
                    [False, False, False, True, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, False, False, True],
                    [False, False, False, False, True, False],
                    [False, False, False, True, False, False],
                    [False, False, True, False, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, False, False, True],
                    [False, False, False, False, True, False],
                    [False, False, True, False, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, True, False],
                    [False, True, False, False, False],
                    [False, False, True, False, False],
                    [False, False, False, True, False],
                    [False, False, False, False, True],
                    [False, False, True, False, False],
                    [False, True, False, False, False],
                    [True, False, False, False, False],
                    [True, False, True, True, True],
                ],
                "file": "1.png",
                "error": "None",
            },
            {
                "qrcode": {
                    "matricule": 20072,
                    "version": "A",
                    "lessonId": "82318c24-3f36-424f-9b29-c1e7e05acfe5",
                },
                "answers": [
                    [False, False, False, False, True, False],
                    [False, False, False, False, True, False],
                    [False, True, False, False, False, False],
                    [False, False, True, False, False, False],
                    [False, True, False, False, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, False, True, False],
                    [False, True, False, False, False, False],
                    [False, False, False, False, True, False],
                    [False, False, False, True, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, False, False, True],
                    [False, False, False, False, True, False],
                    [False, False, False, True, False, False],
                    [False, False, True, False, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, False, False, True],
                    [False, False, False, False, True, False],
                    [False, False, True, False, False, False],
                    [True, False, False, False, False, False],
                    [False, False, False, True, False],
                    [False, True, False, False, False],
                    [False, False, True, False, False],
                    [False, False, False, True, False],
                    [False, False, False, False, True],
                    [False, False, True, False, False],
                    [False, True, False, False, False],
                    [True, False, False, False, False],
                    [False, False, False, True, False],
                ],
                "file": "2.png",
                "error": "None",
            },
        ],
    }
